### ISSUE TITLE
Shop UI - Tango can be sold or dropped/attacked to get the player stuck

### ISSUE THREAD

**Issue by Shushishtok** [ModDota/dota-tutorial#131]
Possible issue: What if the player sells the tangos for half price and then can't buy another set to escape?

Need to make it so when you buy the Tango, you can only move or use the Tango on a tree. All other commands are blocked.

**Comment by olivernybroe** [comment]
Another possible solution could be to just give the player money enough to buy tangos again?

So if the player doesn't have tangos and doesn't have 90 gold, then set the gold to 90.
This would also do if the player sells the tangos, the gold just goes back to 90.

**Comment by Shushishtok** [comment]
That's possible, but it's easier to just disable those things from happening in the first place compared to setting a timer that checks if you have a Tango all the time.
