### ISSUE TITLE
Add shop open detection

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#148]
Right now the shop section just waits 10 seconds instead of actually checking whether the shop is open.

**Comment by VicFrank** [comment]
In Panorama

``
let shopUI = $.GetContextPanel()?.GetParent()?.GetParent()?.GetParent()?.FindChildTraverse("HUDElements")?.FindChildTraverse("shop");

const shopOpen = shopUI?.BHasClass("ShopOpen");
``
