### ISSUE TITLE
UI Highlight gets dislocated when shop is closed

### ISSUE THREAD

**Issue by Shushishtok** [ModDota/dota-tutorial#230]
Trying to highlight an item while the shop is closed, or closing the shop after an item is highlighted will cause the highlight to be placed incorrectly in the HUD.

The UI Highlight should get an optional parameter: `isShopItem`, which is a boolean.
When set to true (which you usually would with items located in the shop), panorama will check if the item is shown.

- If it is: panorama will constantly check if the shop is open (can be done easily via panorama API `Game.IsShopOpen()`). If the shop is closed, the highlight panel becomes invisible until the shop is opened again. This repeats constantly until the highlight panel is removed.
* If it is not: panorama will constantly check if the shop is open. When it is, it will check again for the path of the item, and then match the element's properties to it. It then behaves the same as above.

The general goal is to make the highlight panel only visible when the shop's open and the panel is in place.

**Comment by RobinKa** [comment]
Fixed in #239 (I think)
