### ISSUE TITLE
Observer ward is free in shop, could mess up the inventory slots in later sections

### ISSUE THREAD

**Issue by YoyoyoChang** [ModDota/dota-tutorial#235]
Current behavior: Observer ward is free in shop.

Potential issue: Player could buy wards in Chapter 1 and mess up the inventory slots or goals in later sections.

Expected behavior: Make ward unpurchasable or not free.

**Comment by Perryvw** [comment]
Keep purchase blocked in order filter (think we already do that for part of the tutorial?).

**Comment by Shushishtok** [comment]
Fixed in https://github.com/ModDota/dota-tutorial/pull/319
