### ISSUE TITLE
CH2 buying crystalis early softlocks

### ISSUE THREAD

**Issue by quickcharge3** [ModDota/dota-tutorial#240]
[video of the bug in action](https://cdn.discordapp.com/attachments/820031245319667772/820071188239220746/Dota_2_2021-03-12_17-08-58.mp4)

player is able to spend their gold before the quest appears, softlocking

this happens while slacks line "in order to complete the daedalus, you must..." is displayed

**Comment by Shushishtok** [comment]
I'll make it impossible to buy stuff while dialog is being played.

**Comment by Shushishtok** [comment]
Fixed in https://github.com/ModDota/dota-tutorial/pull/306 forgot to mark it
