### ISSUE TITLE
CH1 Not obvious which greevil is talking

### ISSUE THREAD

**Issue by quickcharge3** [ModDota/dota-tutorial#243]
- [ ]  Highlight sunsfans greevil in some way, health bar is not visible enough
- [ ]  Too much going on in his greevil portrait to make an immediate connection to the ingame model

**Comment by RobinKa** [comment]
Could use a different gesture for the dialog, right now it's the attack animation but maybe we could use a channeling one. Could also put some kind of highlight on the talking one.
