### ISSUE TITLE
Too much camera locking

### ISSUE THREAD

**Issue by quickcharge3** [ModDota/dota-tutorial#246]
- after teaching the player camera controls, don't take them away so much
- ch5 - moving single screen distance on the way to the bounty rune feels especially punishing

**Comment by quickcharge3** [comment]
ch5 - moving single screen distance on the way to the bounty rune feels especially punishing

**Comment by smashthestate** [comment]
Did this for all chapters except CH3, but we decided to not worry about it for now.
