### ISSUE TITLE
CH2 Audio timing

### ISSUE THREAD

**Issue by quickcharge3** [ModDota/dota-tutorial#247]
- [ ] Godz 5/5 final successful last hit audio and sunsfans explanation about using Q to cs seem to happen at the same time
- [x] might be better to not randomize the successful cs playback lines and only randomize the missed cs lines?

**Comment by Shushishtok** [comment]
> might be better to not randomize the successful cs playback lines and only randomize the missed cs lines?

I don't get the issue with that?

**Comment by Shushishtok** [comment]
After talking with @quickcharge3 , no need for the second thing.
