### ISSUE TITLE
Create visual indicators for helping the player

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#26]
Visual indicators will be needed in a lot of places such as pointing players to where they have to go and so on.

Some I could think of now (might already be part of Dota)
- ~~Something highlighting a part of the UI (eg. for pointing to a skill to learn, or making the user look at a part of the UI)~~ https://github.com/ModDota/dota-tutorial/pull/81 although still needs server-side logic
- ~~Arrow pointing the player somewhere on the map~~
- ~~Minimap indicator pointing the player somewhere on the map~~

**Comment by Shushishtok** [comment]
Thinking about some more stuff to use here:

* An arrow above a unit that lets the player know which units he needs to kill to progress. (e.g. creeps)
* An area that the player needs to do his objective in - maybe indicated as a big circle? Where the thing that needs to be done is not just reaching position. (e.g. reach radius of the secret shop.)
* An arrow above a unit that lets the player know that he needs to get close to the target unit. (e.g. mud golem waiting for you to arrive to its new position.

**Comment by quickcharge3** [comment]
maybe the "hero is out of camera range" indicator from the luna tutorial could be changed into saying "'next target' is out of camera range" if the player is supposed to look somewhere -> might encourage looking at minimap to find next target if paired with minimap animation

**Comment by RobinKa** [comment]
UI highlight done in https://github.com/ModDota/dota-tutorial/pull/81

**Comment by RobinKa** [comment]
Toyoka created particles the following particles
- paths with up to 60 control points, eg. for showing the path to objectives
- circle+arrow pointing down, eg. for pointing out interactables
- circle, eg. for highlighting things such as buildings

Once those are implemented I think we have what we need (stuff pointing to enemies could use the above with a red tint).
