### ISSUE TITLE
Sniper should not deny his creeps when the player supposed to deny radiant creeps.

### ISSUE THREAD

**Issue by Flam3sDOTA** [ModDota/dota-tutorial#277]
In the "deny friendly 0/3 creeps" section, sniper denies his own creeps instead of attacking radiant creeps to make the player's task harder. 

Slacks mentioned this in his latest video too. So, Instead, Sniper should attack radiant creeps to make it hard for player to deny his creeps.

**Comment by Shushishtok** [comment]
Not true.
