### ISSUE TITLE
Fork dialogs with goals in all chapters

### ISSUE THREAD

**Issue by Shushishtok** [ModDota/dota-tutorial#280]
To be done after all chapters are done.

Currently, we go in a sequential pattern, where we play dialogs that explain to the user that he has to do something, like leveling up an ability or buying an item. The dialogs must first be resolved (either naturally or with skips) before checking for the objective, usually with completeOnCheck() checks. 

All of those instances should be with forkAny, where the objective is checked in parallel to the dialog. If the objective is done before the dialog, the dialog would also immediately be stopped. The dialog side of all forkAny steps should have a neverComplete() step; it should only complete when the objective is done.

**Comment by Shushishtok** [comment]
Do not include CH6.

**Comment by Shushishtok** [comment]
Also not CH6.

**Comment by smashthestate** [comment]
Did this for all chapters except CH3 and CH6.
