### ISSUE TITLE
CH1 CH2 CH4 Audio overlaps

### ISSUE THREAD

**Issue by quickcharge3** [ModDota/dota-tutorial#284]
- [ ] CH1 leveling Q before sunsfan finishes his "excellent work..." line plays the next line overlapping. _This only happens on a playthrough from the start, not after skipping to the section again. It happens 100% of the time then_

- [ ] CH2 GodZ 5/5 cs line overlaps sunsfans next line _100% of the time, first playthrough or skipping there again doesn't matter here_

- [ ] CH4 before the muting video plays, there is a report of overlap _(I did not manage to reproduce this so far)_

- [ ] Mute DKs lines while dialog is playing?

**Comment by RobinKa** [comment]
Seems like this happens when a dialog step gets stopped (eg. by having it in `forkAny` with another step completing in it).
