### ISSUE TITLE
CH4 - Make sure Riki can not die before he should

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#368]
Possible to get some lucky crits and stun to kill him I think right now

**Comment by RobinKa** [comment]
This is still an issue. Right now Riki only gets the takes no damage modifier durign wards section, but during outpost section he is still killable after dust for example.

**Comment by smashthestate** [comment]
Fixed so he's only killable at the end of outpost section

**Comment by Shushishtok** [comment]
Fixed in https://github.com/ModDota/dota-tutorial/pull/412
