### ISSUE TITLE
Give Slacks and SUNSfan a Hero Health bar instead of Unit Health bar

### ISSUE THREAD

**Issue by Flam3sDOTA** [ModDota/dota-tutorial#388]
They should have health bar like heroes to make their bar more obvious when the line "Why do I have a health bar on me" is active.

If I remember correctly, "ConsideredHero" "1" in the unit kv file should do the trick

![hero](https://user-images.githubusercontent.com/30335579/111602650-9eb6b780-87e4-11eb-8a42-b0c285d9c425.png)

**Comment by RobinKa** [comment]
We should also hide their health bar until they become attackable (because the dialog says "why do I have a health bar").
