### ISSUE TITLE
Explore methods of showing a youtube playlist inside a custom game

### ISSUE THREAD

**Issue by SinZ163** [ModDota/dota-tutorial#4]
* [ ] Embedded Webview
* [ ] Steam Overlay
* [ ] Open default browser

**Comment by olivernybroe** [comment]
For playing the videos ingame, it might be worth playing the videos without using the Youtube player, and then having a Youtube button for letting the OS open a link to the original Youtube video.
This way you can have full control over the video player and easily remove suggestions for other videos + ads. (of course this requires approval from the author)

**Comment by RobinKa** [comment]
For guides we are just showing some info (thumbnail, title, short description) now and opening the default browser when clicking on it.
