### ISSUE TITLE
CH4 feedback after QWR playthrough

### ISSUE THREAD

**Issue by Shushishtok** [ModDota/dota-tutorial#444]
CH4 Wards: Increase size of ward placement location
Change "Use the Dust" to "Use the Dust of Appearance".
Camera pan from player to enemy outpost: needs to start from current hero position.
Riki: "Yes I dont know I'm done" -> fix dont to don't
Camera pans after Well Played from cliff to KOTL.

**Comment by smashthestate** [comment]
![image](https://user-images.githubusercontent.com/8648809/111890377-16553400-89e9-11eb-8cfc-344ba1c4d23f.png)

I was about to change the size of ward placement location but this doesn't look so bad. Max distance from the marker right now is 150.

**Comment by smashthestate** [comment]
> Camera pan from player to enemy outpost: needs to start from current hero position.

It starts from current camera position, it would be pretty weird if it snapped to the current hero's position first no?

> Camera pans after Well Played from cliff to KOTL.
Also starts from current camera position. Could make it not pan at all to KOTL and Kunkka maybe?

**Comment by Shushishtok** [comment]
> ![image](https://user-images.githubusercontent.com/8648809/111890377-16553400-89e9-11eb-8cfc-344ba1c4d23f.png)
> 
> I was about to change the size of ward placement location but this doesn't look so bad. Max distance from the marker right now is 150.

Weird, she tried to click very close to it and basically couldn't. Maybe she presses the wrong button or something? Idk. Seems good.

**Comment by Shushishtok** [comment]
> > Camera pan from player to enemy outpost: needs to start from current hero position.
> 
> It starts from current camera position, it would be pretty weird if it snapped to the current hero's position first no?
> 
> > Camera pans after Well Played from cliff to KOTL.
> 
> Also starts from current camera position. Could make it not pan at all to KOTL and Kunkka maybe?

Both cases I remember it had a snap in both cases. Is it a function in both cases? If it's not, it'll take the camera position that the player had at the section's start.

**Comment by smashthestate** [comment]
> Both cases I remember it had a snap in both cases. Is it a function in both cases? If it's not, it'll take the camera position that the player had at the section's start.

Don't remember exactly the code for the build that she played, but right now it's changed to `_ => getPlayerCameraLocation()` for the starting position in #412  - think there were some `setCameraTarget` calls that might've caused the snapping.

**Comment by Shushishtok** [comment]
Great, if that works as expected now then it's good.

**Comment by smashthestate** [comment]
Resolved all issues listed here
