### ISSUE TITLE
CH5 feedback after QWR playthrough

### ISSUE THREAD

**Issue by Shushishtok** [ModDota/dota-tutorial#445]
CH5: Doesn't show last bounty rune.
CM is male - consider replacing with another hero
Empty line on "Yes, as we watch our heroes..."
Can't hear Sunsfan while Roshan's killing everyone.
Need to highlight the Aegis, and give it FoW viewer until it is taken.
Highlight TP while "Click on the Teleport Scroll" dialog is played.
Looking for it's soulmate -> its
Allow player to actually TP to the base instead of teleporting him

**Comment by smashthestate** [comment]
Most resolved in #460 and by updating localization spreadsheet.

What's left to resolve currently:
- Can't hear Sunsfan while Roshan's killing everyone.
- Allow player to actually TP to the base instead of teleporting him

**Comment by Shushishtok** [comment]
Basically almost everything's here done except for Roshan being too loud. Opening a separate optional issue for it.
