### ISSUE TITLE
Denying quest is not clear

### ISSUE THREAD

**Issue by Perryvw** [ModDota/dota-tutorial#484]
After the dialog is gone it is not clear what to do, proposed to change 'Deny friendly creeps' with something like 'Attack your own creeps to deny the last hit'.

Also people seem to be having issues with hotkeys different than 'A', maybe we can add a tooltip similar to voice with the correct key?

**Comment by xPaw** [comment]
> Also people seem to be having issues with hotkeys different than 'A',

It is actually bound to that for me `"a" = "mc_attack"`, but presssing <kbd>A</kbd> moves the camera (WASD) and the actual button was <kbd>Q</kbd> despite having no actual bind.
