### ISSUE TITLE
Add voice actors to credits

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#486]
Unless they send us their own lines, we can use these below made by Betterson.

Sheepsticked:
Official Beastcoast streamer, fantastic artist, and extraordinary DOTA community member! You can't go wrong with Sheepsticked
https://twitter.com/sheepsticked
twitch.tv/sheepsticked

Sheever:
A beloved host for most of DOTA 2's biggest events! She is unbelievably kind and an inspiration for everyone in the DOTA 2 community!
https://twitter.com/SheeverGaming
https://www.twitch.tv/sheevergaming

ODPixel:
Probably the most iconic DOTA 2 caster in the scene, ODPixel excels at making DOTA moments unforgettable. Chances are if you watch a DOTA 2 clip and hear a British man yelling over it, it's him.
https://twitter.com/ODPixel
Twitch.TV/ODPixel

Mason:
Mason is known for his "passionate" speeches to his teammates during his streams. On top of being one of North America's highest-ranked players, he is a former pro with experience playing in The International! You can learn a lot from him while having a great laugh.
https://twitter.com/masondota
youtube.com/c/Masondota
twitch.tv/masondota2

Cap:
Believe it or not, Cap is more than just a smooth voice. He is one of the highest-ranked casters/analysts in the scene! his quick wits and a great sense of humor make him a pleasure to watch!
https://twitter.com/CapCasts
https://www.twitch.tv/dotacapitalist

Blitz:
From player to caster to coach several times over, Blitz has been through the DOTA scene and knows it like the back of his hand.
https://twitter.com/Blitz_DotA
https://www.twitch.tv/blitzdota

Synderen:
Synderen has been in the DOTA community almost longer than anyone else. He has been in the pro scene since DOTA 1 and the very beginning of the DOTA 2 pro scene as well. Now mainly a caster/analyst, his years of experience are invaluable!
https://twitter.com/syndereNDota
http://twitch.tv/syndereN

Lyrical:
Lyrical is a well-known caster/analyst that helps make DOTA's biggest events as memorable as they can be!
https://twitter.com/LyricalDota
https://www.twitch.tv/lyricaldota

Trent:
DOTA's Canadian treasure, Trent has been a staple caster/analyst for years. Always bringing his wonderful smile to every event, he has helped make a lot of memories through the years.
https://twitter.com/TrentPax
twitch.tv/TrentPax

Arteezy:
North America's Golden Boy, Arteezy is arguably the most loved player in the region. He got into pro DOTA 2 very early and his personality on top of his incredible playstyle has helped turn him into a star. Whenever Arteezy streams, there isn't a single DOTA fan who doesn't know about it.
https://twitter.com/Arteezy
twitch.tv/arteezy
https://www.youtube.com/Arteezy

**Comment by smashthestate** [comment]
Description for PyrionFlax:

`PyrionFlax is a Dota 2 content creator, streamer and host who initially gained recognition with his Youtube series "Pyrion Flax's Guides to Dota 2".`
