### ISSUE TITLE
Video example title box should scale with the length of the title in it

### ISSUE THREAD

**Issue by Perryvw** [ModDota/dota-tutorial#502]
In some languages the title box for video previews is too small and will cause weird cut-offs to happen:

![example](https://cdn.discordapp.com/attachments/318503436226396171/823679820759564359/unknown.png)

**Comment by Flam3sDOTA** [comment]
Fixed
![TitleFix](https://user-images.githubusercontent.com/30335579/112069988-e9865580-8b7d-11eb-8915-421bd7d8f7d6.png)
