### ISSUE TITLE
Create a panel for subtitles for spoken text

### ISSUE THREAD

**Issue by Shushishtok** [ModDota/dota-tutorial#60]
While units will be speaking, subtitles need to be shown to make it easier to understand.
Need to create a panel that will be in the bottom portion of the screen, slightly above the abilities UI. The panel will include:
* The portrait of the unit's speaking.
* The name of the unit's speaking.
* The sentence it is currently saying.

The panel should be not visible by default, and will show up and be hidden by using events.

This needs to be done by two portions:
* Design: Need to design the panel and its portions. We can use design from similar games, such as WC3, while still using Dota themed panels.
* Functionality: Need to hook the panel into events that the server calls, such as showing the text, the portrait, the name of the unit, and whether the panel should be visible or not.

**Comment by RobinKa** [comment]
Implemented in https://github.com/ModDota/dota-tutorial/pull/74
