### ISSUE TITLE
Disable neutral spawners while not needed

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#76]
Should remove all neutral spawner entities (`npc_dota_neutral_spawner`) and manually call spawn neutrals for the stacking section (or re-create the spawners when needed if that doesn't work).

**Comment by Shushishtok** [comment]
Tested code for removing neutrals:
```ts
const spawners = Entities.FindAllByClassname("npc_dota_neutral_spawner");
            print(spawners.length)
            for (const spawner of spawners)
            {
                UTIL_Remove(spawner);
            }
```

**Comment by Wouterz90** [comment]
I don't think we should do this, we can remove and spawn the creeps. We need the creeps to have their behavior around their camps.

Leaving this open as the creep spawn sometimes seems incomplete.

**Comment by Shushishtok** [comment]
Can close, done in CH3 now.
