### ISSUE TITLE
Add dialog skip button logic

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#84]
Right now the skip button on dialogs does nothing / isn't handled yet. We should allow players to skip the dialog with it.

**Comment by VicFrank** [comment]
It works, just not the way text is being used right now. If you give a unit multiple lines of dialog, the player will be able to skip through them. However currently, lines are only given after the current one has already expired.

**Comment by RobinKa** [comment]
If I understand correctly, the way it's currently made the lines would need to come from the same unit. However almost all of our dialogs will have Slacks and Sunsfan talking alternatingly so I think the current way of skipping wouldn't work so perhaps we should just rework it so that the skip button calls some callback `onSkip` that was specified when the dialog was started.
