### ISSUE TITLE
Add Slacks and Sunsfan ghost NPCs

### ISSUE THREAD

**Issue by RobinKa** [ModDota/dota-tutorial#99]
After the mudgolems die they should become ghosts, so we need a flying ghost npc for them.

**Comment by RobinKa** [comment]
Seems like the idea was to kill of the NPCs first so we wouldnt need NPCs following the player so this is not actually needed. But if we have time we can always add this later.

**Comment by Shushishtok** [comment]
Is it a problem to have the golems? We have the infrastructure for them already anyway.

**Comment by RobinKa** [comment]
Closing this for now as this wasn't planned. Can reopen later if we want to add it.
